### PR TITLE
Brainprint PyTests

### PR DESCRIPTION
**Pull request by engrosamaali91**
Method to run brainprint test cases using pytest:
- Create python virtual environment 
- `pip install pytest`
- cd /test_cases
- run command `pytest filename.py `

### CODE REVIEW

**Comment by m-reuter** [comment]
Thanks, can you:
- rebase to current main so that we don't see the changes that were already merged. 
- fix the black error.
- move the test to the brainprint/utils/test directory so that they are run with the other pytest workflows.

**Comment by engrosamaali91** [comment]
In this commit [cd606cd](https://github.com/Deep-MI/BrainPrint/pull/19/commits/cd606cd244bcecb5b2ab3fa17cb8020e1526cdd4)  only errors were resolved. The tests have not been moved to brainprint/utils/test yet.

**Comment by engrosamaali91** [comment]
Apparently [f8a5e9d](https://github.com/Deep-MI/BrainPrint/pull/19/commits/f8a5e9d3933c696cf791a8889c61260664344b2d) automated tests are not possible on github as it requires FREESURFER export and subject directory as well. 
However the pytests for brainprint can be done locally.

**Comment by m-reuter** [comment]
Yes, but are there any tests that can be done without FreeSurfer to be installed? We would not want to install all of FreeSurfer as that is too large and takes too long. But we can replace several of the freesurfer binaries with our own python scripts, for example mri_binarize just combines labels, and there is also code for marching-cube (to extract surfaces), that could increase the number of tests that do not need FreeSurfer.

**Comment by kdiers** [comment]
I think @m-reuter's [comment](https://github.com/Deep-MI/BrainPrint/pull/19#issuecomment-1768657782) touches the more general question how independent of FreeSurfer this software can be already. To my understanding, the only FreeSurfer binaries that we use are `mri_binarize`, `mri_pretess`, `mri_mc`, and `mris_convert` (all of them called in `surfaces.py`). Not exactly sure about `mri_pretess` (and if it's strictly needed), but I think all others could be replaced by python code. We might not be able to exactly reproduce FreeSurfer-based results, but I guess results obtained without FreeSurfer-based code would be valid as well. In that sense, it might be rather an issue of compatibility between versions of this software. Moving away from FreeSurfer would require some development and validation, but if we want to do this, then it would also allow to run all tests remotely - not just some.

**Comment by kdiers** [comment]
Redirecting the pull request from the previous target branch (main) to a new branch (add-tests), because the pull request still needs to be modified, but pushing to the external, forked repository is no longer desired. Will eventually merge the pull request into the new target branch, do necessary modifications, and after that create another PR back into the main branch.

**Pull request merged**
